# Generated by Django 5.2.6 on 2025-10-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("classes", models.CharField(max_length=32)),
                ("gender", models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
