# Generated by Django 5.2.6 on 2025-10-22 03:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "uname",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("upass", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "uprov",
                    models.CharField(
                        default="四川省", max_length=50, verbose_name="区域"
                    ),
                ),
                ("uage", models.PositiveIntegerField(verbose_name="年龄")),
                (
                    "ugender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
                ("udate", models.DateField(verbose_name="生日")),
                ("utel", models.CharField(max_length=11, verbose_name="手机号")),
                (
                    "uphoto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user_photos/",
                        verbose_name="头像",
                    ),
                ),
                ("uurl", models.URLField(blank=True, null=True, verbose_name="主页")),
                ("uemail", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "ubackcolor",
                    models.CharField(
                        default="#000000", max_length=20, verbose_name="喜欢的颜色"
                    ),
                ),
                (
                    "is_agree",
                    models.BooleanField(default=False, verbose_name="同意服务条款"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
            },
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="UserInfo",
        ),
    ]
