# Generated by Django 5.2.6 on 2025-10-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_alter_user_uprov"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
